### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by dano** [toolisticon/annotation-processor-toolkit#84]
I'm using and enjoying this toolkit, but I'd really like to pick up the new `TypeMirror` helpers, so I can completely drop auto-common. Do you plan on doing an official release soon? Thanks!

**Comment by tobiasstamann** [comment]
Hi, 

I'm currently working on further extending that TypeMirror wrapper class.
I will try to do a release including that wrapper class as soon as possible. 

But at the moment i cannot guarantee that the api won't encounter some changes in the near future.

**Comment by tobiasstamann** [comment]
I was able to do the release 0.14.5 today which contains the TypeMirrorWrapper changes.
Have seen that you also have stared the cute framework.  I would be glad to get some feedback or suggestions how to make those frameworks better or to extend them.
Best regards
Tobias

**Comment by dano** [comment]
Thanks!

Let me know if you'd rather I create an issue against `cute` for this, but I do have some feedback there. I was using the filtering feature, and found I needed a filter that wasn't current supported: I wanted to validate if the TypeMirror of the element was equal to another type mirror (basically I wanted to call `TypeUtils.TypeComparison.isTypeEqual(element.asType(), typeMirror)`. The only way I could find to do that was to add an entirely new `CriteriaMatcher`, a `ValidationMessage`, etc.

What I really wanted to do was be able to use the Java streams API, and pass your matchers into `.filter` calls, and then just add my predicate as another filter:
``` java
List<? extends Element> allMembers = ...;
var matchingElement = allMembers.stream()
    .filter(IS_FIELD)
    .filter(BY_MODIFIER).filterByAllOf(FINAL, STATIC))
    .filter(element -> isTypeEqual(element.asType(), typMirrorToMatch))
    .findFirst();
```

But the closest I could get was this, which isn't great:
``` java
var matchingElement =  allTableMembers.stream()
        .filter(IS_FIELD.getMatcher()::check)
        .filter(e -> BY_MODIFIER.getMatcher().checkForMatchingCharacteristic(e, FINAL))
        .filter(e -> BY_MODIFIER.getMatcher().checkForMatchingCharacteristic(e, STATIC))
        .filter(e -> isTypeEqual(e.asType(), typeMirrorToMatch))
        .findFirst();
```

Even supporting some streamlined way of adding a custom filter in cases where I don't care about having a validator would be helpful, something like:
``` java
var matchingElement = createFluentElementFilter(allTableMembers)
        .applyFilter(IS_FIELD)
        .applyFilter(BY_MODIFIER).filterByAllOf(FINAL, STATIC)
        .applyFilter(toFilter(element -> isTypeEqual(element.asType(), typeMirrorToMatch)))
        .getResult()
        .get(0);
```
Where `toFilter` does some magic to turn the user-provided predicate into a type the framework can deal with.

As I've been typing this up I realized that for my use-case I could also do this, which I guess isn't so bad:
``` java
var matchingElement = createFluentElementFilter(allTableMembers)
        .applyFilter(IS_FIELD)
        .applyFilter(BY_MODIFIER).filterByAllOf(FINAL, STATIC)
        .getResult().stream()
        .filter(element -> isTypeEqual(element.asType(), typeMirrorToMatch)))
        .findFirst();
```
Anyway, I don't have a clear ask or solution, but that was one area where I found myself fighting with the framework a bit.

**Comment by tobiasstamann** [comment]
Hi Dano,

thanks for the feedback,. 
I have created most of the filter stuff when I was still pinned on Java 7.
So it's not that optimized for the Java 8 streaming  Api. I am going to check if there is a better way to support it. 

About the TypeMirror Matcher: I can easily add that.I guess I will be able to do that until the end of the week. 

Best regards
Tobias

**Comment by tobiasstamann** [comment]
I know it's a bit late for a feedback, but i was able to move APTK code to Java 8 with release 0.20.0.

With that versions ElementWrappers were added which provide pretty good Java 8  streaming api/lambda support:

```java
// validation - lambda style
Element element = null;
    ElementWrapper.wrap(element).validate()
        .asError().withCustomMessage("Annotation must be placed on static inner class with public or protected modifier")
        .check( ElementWrapper::isClass)
        .and(e -> e.hasModifiers(Modifier.STATIC) && (e.hasModifiers(Modifier.PUBLIC) || e.hasModifiers(Modifier.PROTECTED)))
        .validate();


// Navigation / Filtering
List<TypeElementWrapper> allStaticInnerClasses = ElementWrapper.wrap(element).getAllEnclosingElements().stream()
    .filter(ElementWrapper::isClass)
    .filter(e -> e.hasModifiers(Modifier.STATIC) && (e.hasModifiers(Modifier.PUBLIC) || e.hasModifiers(Modifier.PROTECTED)))
    .map(ElementWrapper::toTypeElement)
    .collect(Collectors.toList());


```
